Don't try to print bits we don't have
INPUT_PROP bits are missing on RHEL6.x and the script would fail with:

  File "./make-event-names.py", line 38, in print_bits
      for val, name in getattr(bits, prefix).items():
      AttributeError: 'Bits' object has no attribute 'input_prop'

Simply bail out if attribute we're looking at isn't defined.

Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>
Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>